POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "change password",
    "emails": ["carloshenrique@teste.com.br"]
}

###

GET http://localhost:3000/campaigns/cvq9a21gnl065853nr40